# Generated by Django 4.2 on 2023-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('nickname', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['-nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18)), name='adult'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('nacionalidad', 'nickname')},
        ),
    ]
